In [10]:
! pip install numpy

In [17]:
import numpy as np

In [20]:
l = list(range(1000))

In [24]:
%timeit [ele**2 for ele in l]

896 µs ± 307 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [25]:
arr = np.array(l)

In [28]:
%timeit arr**2

The slowest run took 4.80 times longer than the fastest. This could mean that an intermediate result is being cached.
4 µs ± 2.63 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [40]:
li = [1,2,3,4,5]

In [41]:
type(li)

list

In [42]:
li + 1

TypeError: can only concatenate list (not "int") to list

In [43]:
li_2 = []
for i in li:
    li_2.append(i + 1)

In [44]:
li_2

[2, 3, 4, 5, 6]

### Arrays

In [45]:
ar = np.array(li)

In [46]:
ar

array([1, 2, 3, 4, 5])

In [47]:
type(ar)

numpy.ndarray

In [49]:
ar *5

array([ 5, 10, 15, 20, 25])

In [52]:
ar.tolist()

[1, 2, 3, 4, 5]

In [53]:
ar

array([1, 2, 3, 4, 5])

In [56]:
# attribute 
ar.ndim

1

In [57]:
ar.shape

(5,)

In [58]:
ar

array([1, 2, 3, 4, 5])

In [59]:
ar[0]

1

In [60]:
ar[-1]

5

In [65]:
# array slicing
ar[-1:-4:-2]

array([5, 3])

In [67]:
ar1 = np.array([5,6,3,2])
ar2 = np.array([1,4,2,1])

In [68]:
ar1

array([5, 6, 3, 2])

In [69]:
ar2

array([1, 4, 2, 1])

In [70]:
ar1 + ar2

array([ 6, 10,  5,  3])

In [71]:
ar1 - ar2

array([4, 2, 1, 1])

In [72]:
ar1 * ar2

array([ 5, 24,  6,  2])

### 2D Arrays

In [78]:
list_2d = [[1,2,3], 
           [4,5,6], 
           [7,8,9]]

In [81]:
arr_2d = np.array(list_2d)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
arr_2d.shape

(3, 3)

In [84]:
arr_2d.ndim

2

In [85]:
arr_2d[0][0]

1

In [87]:
# arr_2d[2][2]
arr_2d[2,2]

9

In [93]:
arr_2d[0]

array([1, 2, 3])

In [ ]:
# array slicing in 2D

# arr[start_row_idx : end_row_idx +1 ,  start_col_idx : end_col_idx + 1]

In [98]:
arr_2d[1 : 3 , 1 : 3]

array([[5, 6],
       [8, 9]])

In [104]:
arr_2d[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
arr_2d[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [130]:
arr_rand = np.random.randint(10, 100, size = (5,5))

In [131]:
arr_rand

array([[75, 71, 12, 50, 15],
       [19, 45, 81, 84, 54],
       [64, 58, 20, 79, 31],
       [51, 27, 32, 42, 45],
       [54, 46, 85, 21, 48]])

In [132]:
arr_rand[3: , :]

array([[51, 27, 32, 42, 45],
       [54, 46, 85, 21, 48]])

In [133]:
arr_rand[1: , : 2 ]

array([[19, 45],
       [64, 58],
       [51, 27],
       [54, 46]])

In [140]:
list_3d = [[[1,2,3], [4,5,6], [7,8,9], [10,11,12]],
          [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]]

arr_3d = np.array(list_3d)

In [141]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [136]:
arr_3d.ndim

3

In [142]:
arr_3d[1, 2 , :]

array([7, 8, 9])

In [143]:
np.random.randint(10, 100, size = (5,5, 5))

array([[[69, 64, 46, 25, 56],
        [36, 90, 23, 96, 25],
        [37, 88, 96, 30, 96],
        [12, 84, 15, 46, 69],
        [40, 24, 13, 41, 84]],

       [[18, 16, 45, 31, 78],
        [87, 59, 12, 97, 24],
        [81, 66, 82, 13, 12],
        [52, 90, 71, 84, 32],
        [76, 52, 43, 49, 60]],

       [[55, 71, 85, 30, 85],
        [93, 69, 63, 21, 89],
        [18, 36, 32, 26, 30],
        [33, 21, 32, 17, 93],
        [77, 15, 16, 97, 86]],

       [[13, 34, 37, 31, 94],
        [51, 30, 50, 52, 92],
        [85, 13, 28, 48, 42],
        [56, 25, 66, 57, 90],
        [67, 29, 35, 58, 80]],

       [[50, 93, 10, 35, 96],
        [10, 33, 51, 81, 42],
        [26, 97, 17, 31, 41],
        [47, 79, 49, 92, 90],
        [68, 25, 30, 51, 20]]])

In [144]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
arr_rand_2d = np.random.randint(0, 10, size= (3,3))

In [147]:
arr_rand_2d

array([[4, 9, 5],
       [5, 6, 7],
       [6, 0, 5]])

In [148]:
# element wise operation
arr_2d + arr_rand_2d

array([[ 5, 11,  8],
       [ 9, 11, 13],
       [13,  8, 14]])

In [149]:
#  element wise multiplication
arr_2d * arr_rand_2d

array([[ 4, 18, 15],
       [20, 30, 42],
       [42,  0, 45]])

In [151]:
#  dot product -> Matrix multiplication
np.dot(arr_2d, arr_rand_2d)

array([[ 32,  21,  34],
       [ 77,  66,  85],
       [122, 111, 136]])

In [152]:
np.dot?

In [155]:
arr_rand_2d

array([[4, 9, 5],
       [5, 6, 7],
       [6, 0, 5]])

In [154]:
np.transpose(arr_rand_2d)

array([[4, 5, 6],
       [9, 6, 0],
       [5, 7, 5]])

In [173]:
arr_rand_2d.T # takes transpose

array([[4, 5, 6],
       [9, 6, 0],
       [5, 7, 5]])

In [160]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [171]:
np.ones((4,4), dtype='int',)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [162]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [165]:
np.diag([1,89,3,4])

array([[ 1,  0,  0,  0],
       [ 0, 89,  0,  0],
       [ 0,  0,  3,  0],
       [ 0,  0,  0,  4]])

In [167]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [170]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [174]:
arr = np.arange(20)

In [175]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [177]:
arr = arr.reshape((5,4))

In [187]:
arr = arr.reshape((10,2))

In [188]:
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [189]:
arr.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [193]:
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [192]:
arr.max()

19

In [194]:
arr.min()

0

In [195]:
arr.sum()

190

In [196]:
arr.mean()

9.5

In [197]:
arr.sum(axis = 0)

array([ 90, 100])

In [201]:
arr.sum(axis = 1)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37])

In [205]:
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [206]:
np.sin(0)

0.0

In [207]:
np.tan(1)

1.557407724654902

In [210]:
# masking
arr > 6

array([[False, False],
       [False, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [212]:
np.exp(10)

22026.465794806718

In [215]:
np.log(10)

2.302585092994046

In [217]:
np.floor(9.6)

9.0

In [218]:
np.ceil(9.6)

10.0

In [220]:
round(9.66666, 2)

9.67

### Stacking

In [221]:
a1 = np.random.randint(0, 10, size= (5,2))
a2 = np.random.randint(0, 10, size= (5,2))

In [222]:
a1

array([[8, 4],
       [1, 1],
       [0, 9],
       [3, 1],
       [9, 2]])

In [223]:
a2

array([[3, 1],
       [9, 2],
       [5, 2],
       [0, 6],
       [6, 5]])

In [225]:
np.hstack((a1, a2))

array([[8, 4, 3, 1],
       [1, 1, 9, 2],
       [0, 9, 5, 2],
       [3, 1, 0, 6],
       [9, 2, 6, 5]])

In [227]:
np.vstack((a1,a2))

array([[8, 4],
       [1, 1],
       [0, 9],
       [3, 1],
       [9, 2],
       [3, 1],
       [9, 2],
       [5, 2],
       [0, 6],
       [6, 5]])